### PR TITLE
Added microservice

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
@Blackbaud-BobbyEarl: Hopefully the README is easier to follow. Thanks for your feedback!

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-HalleyCoplin: Would also like your input when you get the opportunity!

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-SteveBrush Would it be possible to pass the environment when executing `dotnet run`?  https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-run

That would remove the export vs set section of the README.md.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl: Good idea; done. What else ya got? 👍

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks @Blackbaud-SteveBrush!  I've got nothing else.

**Pull request merged**
